### ISSUE TITLE
Investigate OpenEO Terrascope backend credit use for extractions

### ISSUE THREAD

**Issue by kvantricht** [WorldCereal/worldcereal-classification#28]
We should investigate why we have a rather high resource usage for simple METEO + WorldCereal Label extraction jobs running on Terrascope backend.

Example job ID: vito-j-240307b1cee042f6aa0320e8e5ada33c
Resource usage: 47 credits (0.47€)

This for only 1km X 1km patch for one year. This seems a bit suspicious.

**Comment by jdries** [comment]
First guess: job options are set to 9GB memory and 4 cpu's, (4cpu's per task, so not running multiple tasks per executor).
Dividing by 4 could be possible, which would also bring the credits into a more normal range.

**Comment by jdries** [comment]
Conclusion:
- this graph also runs as a synchronous call, it only takes about 2 minutes, so that would be the cheapest way
- batch job with default settings also works, but still costs 34 credits. Probably default settings are still too high and can be tuned down.
- The root cause for expensive batch job is that the process graph is fairly complex, with lots of merge_cubes, meaning a lot of the time executors are allocated but not doing a lot.
- For some reason, openEO needs to determine the band count by evaluating the rdd at least for some of the cubes, making this effect of too many stages a bit worse.
- Another optimization could be to automatically reduce tile size from 256x256 to 128x128, which could decrease memory needs further.
