### ISSUE TITLE
Pixel based crop calendar improvements

### ISSUE THREAD

**Issue by kvantricht** [WorldCereal/worldcereal-classification#9]
@WorldCereal/valencia-team please assign to key person(s) that will be working on this.

- Use LSP metrics to reinfroce the input data into the crop calendars’ model​
- Double check the definition of Summer 1 and Summer 2 calendars.​

**Comment by angui3** [comment]
We have revisited our dataset because we suspected some regions might were experiencing trouble when modelling them as a result of a bias in the dataset. We added new points to around 770. The new points introduced offered a new dataset with a more homogenius range of doys. In doing so the model shows an improvement. We also applied the hypothesis of tropical points introducing some noise in the non-tropical areas. By separating data in two different dataset we have also seen a better response of the model, thus reducing the residuals to less than 20 days in non-tropical points. The two attached images show the different behaviour of the model for non-tropical points when training with all the data together and when training only with non-tropical points.

![Image](https://github.com/WorldCereal/worldcereal-classification/assets/131772185/f067e4c5-6a9b-41c0-bb75-11f0524c571b)
![Image](https://github.com/WorldCereal/worldcereal-classification/assets/131772185/7bafb8c9-f83b-47d8-8c9a-bba2687f94f7)

**Comment by kvantricht** [comment]
Still todo:
- collect new data for retraining the maize model in tropical areas
- create up to two maize seasons
- merge one of the two maize seasons with the wheat season to result globally in two (chronological) seasons

**Comment by angui3** [comment]
The last version of the wheat model produce these results for SOS and EOS:

![Image](https://github.com/WorldCereal/worldcereal-classification/assets/131772185/898151c6-bce3-404f-ad55-c19d329001bd)

![Image](https://github.com/WorldCereal/worldcereal-classification/assets/131772185/8f43dcc8-c1e4-4586-a33b-500ad6eb30c9)

We are already developing the new model for maize

**Comment by kvantricht** [comment]
First new version as pixel-based calendars (2 seasons globally) to be uploaded to /vitodata/worldcereal and share with the team for feedback.

**Comment by angui3** [comment]
The first version of the new maize season is completed. Grown from 443 points in Phase I to 575 in Phase II. For both start of season and end of season R^2 is now 0.96 from previous 0.84 and 0.79 respectively. RMSE for SOS has dropped from 22.47 to 17.19 and the EOS from 28.37 to 18.18. 

![Image](https://github.com/WorldCereal/worldcereal-classification/assets/131772185/953ca7e9-2e1d-4462-9112-ff75b55c4cd7)



![Image](https://github.com/WorldCereal/worldcereal-classification/assets/131772185/d0e735aa-eb41-4820-8ec9-2829e071c34b)



![Image](https://github.com/WorldCereal/worldcereal-classification/assets/131772185/1e1f2b7f-71c4-430f-afe7-d04480ca9da8)

**Comment by kvantricht** [comment]
Where is this first version? Is it available in in GeoTIFF format?

**Comment by jdegerickx** [comment]
Please add new version of crop calendars to worldcereal mount on Terrascope: create a new subfolder "Phase_II" in /vitodata/worldcereal/data/cropcalendars

**Comment by angui3** [comment]
I'm still configurating Terrascope, I share them here:
[Crop Calendars Definitius.zip](https://github.com/user-attachments/files/15901923/Crop.Calendars.Definitius.zip)

**Comment by angui3** [comment]
It seems that I only have access to the public WorldCereal data. I don't know if I should ask for permissions in the forum. The username I used when signing up was 'angui'.

**Comment by kvantricht** [comment]
We can put it there for the time being, don't worry about it. I downloaded the ZIP and saw the calendars being names `ww` and `m1`. But as you know, we agreed on needing chronological seasons for the new system, not direct links to wheat and maize (check one of my comments a bit higher in this thread).

So could you also make a version of `s1` and `s2` where, as agreed, every pixel gets for `s1` the seasonality of whichever of the two seasons (ww and m1) ends first in the calendar year, and `s2` gets the seasonality of the other one.

**Comment by jdegerickx** [comment]
quickly comparing the new to the old calendars, I noticed the spatial coverage of the new calendars is quite different, with several smaller islands and deserts/tropical forests missing. Is this spatial extrapolation still to be expected in a future update or should the system be able to deal with these missing areas?

**Comment by jdegerickx** [comment]
Also another thing I noticed, is that the new rasters are floats and have np.nan as nodata value.
Could this be changed to int16 and 0 as nodata value, to be aligned with previous versions of the calendars?

**Comment by kvantricht** [comment]
> quickly comparing the new to the old calendars, I noticed the spatial coverage of the new calendars is quite different, with several smaller islands and deserts/tropical forests missing. Is this spatial extrapolation still to be expected in a future update or should the system be able to deal with these missing areas?

"deal with" as in not fail when a NaN (0) is encountered can be implemented but it's of course not something that we want. We can't let the coarse resolution crop calendars impose where cropland cannot occur. So to be able to run globally, we need to have calendar values over all land masses.

**Comment by kvantricht** [comment]
Another thing I noticed is the sometimes very big difference between neighboring pixels. Even if the color difference is due to the year crossing, I see examples of one pixel having a DOY of 252 and the next one having a DOY of 33. That's a difference of 146 days between neighboring pixels, which will surely lead to artefacts.

![image](https://github.com/WorldCereal/worldcereal-classification/assets/66418796/d239b7c9-1bf0-43e1-aba7-397228dd0c40)

**Comment by angui3** [comment]
I attach the chronological calendars with int16 and 0 as nodata value. I've also included the updated statistics for the Phase I AEZ.
About the missing desert/tropical forests/islands, yes, in the next version they'll be included. However, as there aren't remarkable active croplands there, the extrapolation of data might not be indicative of what the actual agricultural practices are in these regions.

Can you specify from which region and calendar the screenshot is so I can check it and see what's happening?
 
[Chronological Calendars and Updated Phase I.zip](https://github.com/user-attachments/files/15912818/Chronological.Calendars.and.Updated.Phase.I.zip)

**Comment by kvantricht** [comment]
> I attach the chronological calendars with int16 and 0 as nodata value. I've also included the updated statistics for the Phase I AEZ. About the missing desert/tropical forests/islands, yes, in the next version they'll be included. However, as there aren't remarkable active croplands there, the extrapolation of data might not be indicative of what the actual agricultural practices are in these regions.
> 
> Can you specify from which region and calendar the screenshot is so I can check it and see what's happening?
> 
> [Chronological Calendars and Updated Phase I.zip](https://github.com/user-attachments/files/15912818/Chronological.Calendars.and.Updated.Phase.I.zip)

I understand, but we had that discussion in Phase I too and we still need full coverage even if there's hardly any cropland. It's easy to miss some small croplands in the coarse calendar product so it's better to have the extrapolation in those areas too.

As for the big jumps in SOS/EOS, the example was from Latin America:

![image](https://github.com/WorldCereal/worldcereal-classification/assets/66418796/ecfc1e9a-863f-4278-b49a-706c58d436ae)

But I see blocky artefacts with rather large jumps in multiple occasions: 

![image](https://github.com/WorldCereal/worldcereal-classification/assets/66418796/435ad95c-4ff7-4407-8295-b43fad6dff2e)

![image](https://github.com/WorldCereal/worldcereal-classification/assets/66418796/2d6704a7-206a-4560-9a1f-d36125a3b350)

**Comment by angui3** [comment]
Yes, I see what you mean. I'll try to provide a version with all lands covered and with smoother changes asap.

**Comment by jdegerickx** [comment]
Perhaps already another note on the length of the seasons. I recently visited Indonesia, where the maize season tends to last quite long (6-7 months, from what I heard). However, I see the seasons you defined there only cover 3 months. I'm a bit afraid that by defining them this narrow, we will miss out parts of the season (also because there is quite a large variability in calendars in these tropical regions). We also want to capture other temporary crops in our seasons, aside from corn and wheat and by keeping them rather limited, we risk missing out other crops which are perhaps slightly out of sync with the peak period of maize. Please also have a look at the range of SOS and EOS as defined by USDA, attached.

What is your vision on this?

![Image](https://github.com/WorldCereal/worldcereal-classification/assets/66786145/9575d2a0-2f97-4638-a9af-e563637bdd6f)

**Comment by angui3** [comment]
I have updated the calendars to include data for all the emerged lands. We are still analysing the regions with artifacts and huge transitions. 

For the Indonesia case, it is true that length of season is problematic. We are relying more on the Crop Monitor data, but still, the seasons should be expanded. Season 2 now spans from may to august but it should be extended to september (according to Crop Monitor). And the similar should be done with the season 1.
 

[season1&2calendars_v2.zip](https://github.com/user-attachments/files/15991485/season1.2calendars_v2.zip)

**Comment by jdegerickx** [comment]
OK I see you changed no data to zero, that's good, however:
- data type of the raster files is still float32 --> please change to Int16 in next version
- the nodata value is not embedded correctly in the raster files metadata --> please fix for next version
- you changed the CRS to EPSG:3857. Is there a particular reason for this? @kvantricht, if I'm not wrong, the processing module expects EPSG:4326 for the crop calendars...

**Comment by kvantricht** [comment]
Indeed, CRS should be EPSG:4326; UV team please do thorough quality checks before sending updated versions of the calendars, otherwise we have too many useless iteration cycles.

**Comment by angui3** [comment]
Here is the version we showed at the Milestone 1 meeting. Now it should be in int16, nodata=0 and epsg:4326.

[calendars_last_version.zip](https://github.com/user-attachments/files/16125649/calendars_last_version.zip)
[Updated AEZ.zip](https://github.com/user-attachments/files/16125650/Updated.AEZ.zip)

**Comment by kvantricht** [comment]
Next version will be ready **first week of September**

**Comment by angui3** [comment]
We have changed the model algorithm from random forest to xgboost and integrated the LSP new points and the new model show these results:
![Image](https://github.com/user-attachments/assets/91970043-b0ef-4e0d-95c0-bdc53fdc40cb)
![Image](https://github.com/user-attachments/assets/b172bb16-a4fa-45a4-a402-53f1b64c7973)
![Image](https://github.com/user-attachments/assets/17c93e46-46c0-4077-8ea2-1443f3222550)
![Image](https://github.com/user-attachments/assets/6d475003-9502-4176-b278-d0224561af8b)

**Comment by angui3** [comment]
Here are the latest version of the calendars, both the winter-summer crops classification and the derived s1s2 calendars. As we comented during last week meeting we used a new xgboost model with all the data from the LSP integration. We are using these results to produce the new aezs.   
[crop_calendars.zip](https://github.com/user-attachments/files/17013465/crop_calendars.zip)

**Comment by kvantricht** [comment]
One thing I already observed is that the coverage of the new calendars is a bit smaller than the previous ones. We had these discussions in phase I, where some pixels were no data because close but not entirely over ocean. Juanma then buffered this a bit outward if I recall. I guess the minimum requirement is that we have the same coverage extent as the previous ones.

**Comment by angui3** [comment]
Yes, I see that in some islands there are missing pixels in comparison with Juanma. I will upload as soon as possible the expanded version.

**Comment by jdegerickx** [comment]
@angui3, @MolettoLobos I had a quick look. In tropical regions, the crop calendars still look rather noisy. In these regions I see pixels with growing seasons lasting less than 10 days. We would like to integrate the calendars in the system v1 release, but not in the current state. They still require decent post-processing and quality checks.

**Comment by angui3** [comment]
The tropical regions have been modified to obtain smoother calendars. The lengths of season have been checked and the extreme values deleted and interpolated. We adjunct the case of Indonesia for winter crops. Although some Indonesian islands haveregional variations, we have processed it in order to achieve <30 doys of variance between near zones. We still have to manage the feedback received by the INPE and OneAcreFund and incorporate the changes proposed for Brazil and Kenya. We're trying to have a meeting with them for early next week. 

![Image](https://github.com/user-attachments/assets/a45bde2b-f6e7-4978-9b2a-2c617f947490)
![Image](https://github.com/user-attachments/assets/e81108b8-7d91-4d13-be99-cd2e70ed62b5)
![Image](https://github.com/user-attachments/assets/92714d3c-73a8-4605-a10e-b49ea9ddd449)
![Image](https://github.com/user-attachments/assets/da378578-4e73-4475-82fd-903d7090f47b)
![Image](https://github.com/user-attachments/assets/13fcb13c-f934-4271-b2d0-b7ee18df4622)
![Image](https://github.com/user-attachments/assets/5c85963f-5065-4b17-b80d-7500fb3d535b)

**Comment by jdegerickx** [comment]
Looking promising! Still see some sharp transitions here and there, so we need to make sure the AEZ borders nicely follow these transitions, otherwise we'll get artefacts in the global products...
Thanks!

**Comment by jdegerickx** [comment]
@kvantricht, I suggest to close this issue as we have defined more detailed issues based on today's meeting...

**Comment by kvantricht** [comment]
Closing as this issue is now tracked in multiple follow-up issues.
